export interface ReadmeInput {
  name: string;
  slug: string;
  role: string;
  skills: string[];
}

/**
 * Produces the markdown README that ships at the top of the colleague agent
 * zip bundle. The same string is rendered as install instructions on
 * `/wizard/download` (Page 5) — single source of truth.
 *
 * Pure function, no I/O.
 */
export function buildReadme(input: ReadmeInput): string {
  const { name, slug, role, skills } = input;

  const skillLines = skills
    .map((s) => `  - \`.claude/skills/${s}/SKILL.md\``)
    .join('\n');

  return `# ${name} — Colleague Agent

A Claude Code agent package generated by the Colleague Agent Builder.

## What's inside

- \`.claude/agents/${slug}.md\` — the agent file (persona + capabilities)
- \`.claude/skills/\` — ${skills.length} bundled skill template${skills.length === 1 ? '' : 's'}:
${skillLines}
- \`.mcp.json\` — Model Context Protocol server config (knowledge base access)
- \`meta.json\` — package metadata (role, slug, skill list, created-at)

## Install in Claude Code

1. Unzip this package into the root of your Claude Code project.
2. Restart Claude Code so the new agent and skills are discovered.
3. Ask Claude: "Use the ${slug} agent to ..." or invoke it directly via the Agent tool.

## Using with OpenClaw, Codex, or other tools

The \`.claude/skills/\` folder and \`.mcp.json\` are portable — OpenClaw reads
the same skill format, and any tool supporting the Model Context Protocol can
consume \`.mcp.json\` for knowledge-base access. The
\`.claude/agents/${slug}.md\` file uses the Claude Code agent format — other
tools (Codex, bespoke harnesses) may need manual adaptation of the
frontmatter and tool-invocation syntax, but the persona body itself is plain
markdown and transfers cleanly.

## Role

This agent's role is **${role}**.
`;
}
